import {
  BeakerIcon,
  BoltIcon,
  PaintBrushIcon,
  MusicalNoteIcon,
  PuzzlePieceIcon,
  SparklesIcon,
  BookOpenIcon,
  UserGroupIcon,
  LightBulbIcon,
  ChartBarIcon,
  SunIcon,
  StarIcon,
  ChartPieIcon,
} from "@heroicons/react/20/solid";

export const Icons = {
  BeakerIcon,
  BoltIcon,
  PaintBrushIcon,
  MusicalNoteIcon,
  PuzzlePieceIcon,
  SparklesIcon,
  BookOpenIcon,
  UserGroupIcon,
  LightBulbIcon,
  ChartBarIcon,
  SunIcon,
  StarIcon,
  ChartPieIcon,
};
